name: CI-Pipeline

on:
  push:
    branches: [ main ]
    paths-ignore:
      - 'kubernetes/deployment.yaml'
      - 'helm/devsecops-chart/values.yaml'
  pull_request:
    branches: [ main ]

jobs:
  checkout-code:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

  install-dependencies:
    needs: checkout-code
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - name: Install Dependencies
        run: npm ci

  run-tests:
    needs: install-dependencies
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - name: Install Dependencies
        run: npm ci

      - name: Run Unit Tests
        run: npm test

  static-code-analysis:
    needs: install-dependencies
    runs-on: ubuntu-latest

    steps:
      - name: checkout-code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - name: Install Dependencies
        run: npm ci

      - name: Run Lint
        run: npm run lint

  build-application:
    needs: static-code-analysis
    runs-on: ubuntu-latest

    steps:
      - name: checkout-code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - name: Install Dependencies
        run: npm ci

      - name: Build-Application
        run: npm run build

      - name: Upload Build Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: build-artifacts
          path: dist/
    
  build-docker-image:
    needs: build-application
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GH_PAT}}

      - name: Build and Push Docker Image
        run: |
          docker build -t ghcr.io/${{ github.repository }}/devsecops:${{ github.run_number }} .

      - name: Push Docker Image
        run: |
          docker push ghcr.io/${{ github.repository }}/devsecops:${{ github.run_number }}

      - name: Scan Image with Trivy
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: 'ghcr.io/${{ github.repository }}/devsecops:${{ github.run_number }}'
          format: 'table'
          exit-code: 1
          severity: 'CRITICAL,HIGH'

  update-newtag-in-helm-chart:
    needs: build-docker-image
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.TOKEN }}

      - name: Update Image Tag in Helm Chart
        run: |
          sed -i "s|tag: .*|tag: \"${{ github.run_number }}\"|g" helm/devsecops-chart/values.yaml

      - name: Commit and push changes
        run: |
          git config --global user.email "jaychandra@gmail.com"
          git config --global user.name "jaychandra17"
          git add helm/devsecops-chart/values.yaml
          git commit -m "Update tag in Helm chart"
          git push
